on:
  workflow_run:
    workflows: ["Nexon Marketing Marketing Docker Push"]
    types: [requested]
    branches:
      - 'releases/**'
      - 'feat/**'
      - dev

#############################################################################################
# Passing global environment variable, this can be use throughout the file 
env:
  ECR_REGION: us-east-1
  ECR_PROFILE: nexon-dev
#############################################################################################

jobs:
###############################################################################################################################################################################
#     Task Definition register
#     Task Definition will register with new image version using a bash script to cat the version number from version file in the root and append it as a variable in docker tag
###############################################################################################################################################################################

  Task-Definition:
    runs-on: self-hosted
    name: Register TaskDefinition
    environment:
      name: Dev
    defaults:
      run:
        shell: bash
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: "register-task-definition"
        run: |
            cd nexon-marketing-CD && sed -i s/"{{version}}"/$(cat ../version.sh | cut -c 9-)/g nexon-marketing-CD/task-definition.json
            aws ecs register-task-definition --profile $ECR_PROFILE --region $ECR_REGION --cli-input-json file://task-definition.json
    needs: [Push]

##################################################################################################################################################################
#    Update ECS Service
#    Service update will be the last step, 1st it will update the service with 0 desired count to kill old running tasks and then update it again with new count.
##################################################################################################################################################################

  Update-Service:
    runs-on: self-hosted
    name: Update Service
    defaults:
      run:
        shell: bash
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        env:
          SERVICE: nexon-development-xqzpf
          TASKDEFINITION: nexon-development-task-definition-xqzpf
          COUNT: 2
          CLUSTER: nexon-development-ecs-cluster-xqzpf
        name: "Update-Service"
        run: |
            aws ecs update-service \
            --service $SERVICE \
            --task-definition $TASKDEFINITION \
            --desired-count 0 \
            --profile $ECR_PROFILE \
            --region $ECR_REGION \
            --cluster $CLUSTER

            sleep 100

            aws ecs update-service \
            --service $SERVICE \
            --task-definition $TASKDEFINITION \
            --desired-count $COUNT \
            --profile $ECR_PROFILE \
            --region $ECR_REGION \
            --cluster $CLUSTER

    needs: [Task-Definition]
