on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches: 
      - dev
      - 'releases/**'
#########################
Task Definition register
#########################
jobs:
  Task-Definition:
    runs-on: self-hosted
    name: register-task-definition
    environment:
      name: Dev
    defaults:
      run:
        shell: bash
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        env:
          ECR_REGION: us-east-1
          ECR_PROFILE: nexon-dev
        name: "register-task-definition"
        run: |
            sed -i 's/"{{version}}"/$(cat version.sh | cut -c 9-)/g' task-definition.json
            aws ecs register-task-definition --profile $ECR_PROFILE --region $ECR_PROFILE --cli-input-json file://task-definition.json
