on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main    
      - dev
      - 'releases/**'

jobs:
  Docker-Login:
    runs-on: self-hosted
    name: Login
    defaults:
      run:
        shell: bash
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        env:
          ECR_REGION: us-east-1
          ECR_PROFILE: nexon-dev
        name: "docker_login"
        run: |
            $(cat version.sh | cut -c 9-)
            aws ecr get-login-password --region $ECR_REGION --profile $ECR_PROFILE | docker login --username AWS --password-stdin 126609036647.dkr.ecr.us-east-1.amazonaws.com

  Build:
    runs-on: self-hosted
    name: Nexon Marketing Application Build

    defaults:
      run:
        shell: bash
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: "build"
        run: |
            docker build -t nexon-marketing:$(cat ../../nexon-marketing-CI/version.sh | cut -c 9-)
    needs: [Docker-Login]

  Push:
    runs-on: self-hosted
    name: Nexon Apllication Push

    defaults:
      run:
        shell: bash
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: "push"
        run: |
            docker tag nexon-marketing:$(cat ../../nexon-marketing-CI/version.sh | cut -c 9-) 126609036647.dkr.ecr.us-east-1.amazonaws.com/nexon-development-zgqad:$(cat ../../nexon-marketing-CI/version.sh | cut -c 9-)
            docker push 126609036647.dkr.ecr.us-east-1.amazonaws.com/nexon-development-zgqad:$(cat ../../nexon-marketing-CI/version.sh | cut -c 9-)
    needs: [Build]
